---
- hosts: 127.0.0.1
  connection: local
  tasks:
   - name: get solarized
     git: repo=https://github.com/altercation/solarized.git
          dest=./solarized
   - name: get liquid promt
     git: repo=https://github.com/nojhan/liquidprompt.git
          dest=~/liquidprompt
   - name: add liquid prompt to bash rc
     lineinfile: "dest=~/.bashrc line='source ~/liquidprompt/liquidprompt'"
   - name: get bash solarized
     git: repo=https://github.com/Anthony25/gnome-terminal-colors-solarized.git
          dest=./gnome-solarized
   - name: install bash solarized
     script: ./gnome-solarized/install.sh
